apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/arch-loom-v2/fabric.gradle"

loom {
    accessWidenerPath.set file("src/main/resources/improvedmobs.accesswidener")
}

ext {
    mod_meta.tenshilib_version = tenshilib_version
    mod_meta.forge_config_api = forge_config_api
}

repositories {
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
    }
}

dependencies {
    modImplementation "io.github.flemmli97:tenshilib:${tenshilib_version}-fabric"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api}"

    //CompileOnly cause not getting all deps... get a maven pls
    modCompileOnly "${playerex}"
    modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-base:4.2.0"
    modCompileOnly "${levelz}"

    modRuntimeOnly "io.github.flemmli97:debugutils:1.21.1-1.0.8-fabric"
}