plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '2.0.107' apply false
    id 'io.github.flemmli97.multiloader.discord_hook' version '1.+'
}

subprojects {
    repositories {
        mavenLocal()
        maven {
            name = "TenshiLib"
            url = "https://maven.blazing-coop.net/releases"
            content {
                includeGroup 'io.github.flemmli97'
            }
        }
        maven {
            name = "Fuzs Mod Resources"
            url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
            content {
                includeGroup 'fuzs.forgeconfigapiport'
            }
        }
        maven {
            name = "CurseMaven"
            url = "https://www.cursemaven.com"
            content {
                includeGroup 'curse.maven'
            }
        }
        maven {
            url = "https://api.modrinth.com/maven"
            content {
                includeGroup 'maven.modrinth'
            }
        }
    }
}