org.gradle.jvmargs=-Xmx3G
enabled_platforms=fabric,neoforge
minecraft_version=1.21.1
neoForm_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28
# NeoForge Properties
neo_loader_version=2
neoforge_version=21.1.233
# Fabric Properties
fabric_loader_version=0.16.14

# Mod Properties
mod_version=1.15.2
maven_group=io.github.flemmli97
mod_id=improvedmobs
mod_author=flemmli97

# Dependencies
fabric_version=0.116.4+1.21.1
tenshilib_version=1.21.1-2.2.3
cardinal_comp=6.1.2
levelz=curse.maven:levelz-517130:6181516
forge_config_api=21.1.3
runecraftory_version=1.21.1-2.0.0-beta
powerscale_dep=curse.maven:powerScale-1155398:6333313
sillib_dep=curse.maven:silentLib-242998:6565251
# not updated
playerex=curse.maven:playerex-958325:6007064

# Curse properties
curse_versions=1.21.1, Java 21
curse_page_fabric=https://www.curseforge.com/minecraft/mc-mods/improved-mobs-fabric
curse_id_fabric=552968
curse_dep_fabric=fabric-api, tenshilib-fabric
curse_page_forge=https://www.curseforge.com/minecraft/mc-mods/improved-mobs
curse_id_forge=282639
curse_dep_forge=tenshilib
modrinth_versions=1.21.1
modrinth_page=https://modrinth.com/mod/improved-mobs
modrinth_id=23MovWyi
modrinth_dep_fabric=fabric-api, tenshilib
modrinth_dep_forge=tenshilib

# Other
project_name=Improved Mobs
full_changelog=https://github.com/Flemmli97/ImprovedMobs/blob/1.21/Changelog.md
discord_role=852113512214036530
