apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/arch-loom-v2/common.gradle"

loom {
    accessWidenerPath.set project(":fabric").file("src/main/resources/improvedmobs.accesswidener")
}

dependencies {
    modCompileOnly "io.github.flemmli97:tenshilib:${tenshilib_version}-common"
    modCompileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api}"

    modCompileOnly "io.github.flemmli97:runecraftory:${runecraftory_version}-common"
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}