plugins {
    id 'io.github.flemmli97.multiloader.platform-common'
}

dependencies {
    compileOnly "io.github.flemmli97:tenshilib:${tenshilib_version}-common"
    compileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api}"

    commonDependency "io.github.flemmli97:runecraftory:${runecraftory_version}-common"
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}
