plugins {
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.flemmli97.multiloader.platform-neoforge'
}

neoForge {
    runs {
        var common = project(":common")
        data {
            data()
            programArguments.addAll "--all", "--mod", "improvedmobs"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
            programArguments.addAll "--existing", file("src/main/resources").absolutePath
            programArguments.addAll "--existing", common.file("src/main/resources").absolutePath
        }
        client {
            jvmArgument "-XX:+AllowEnhancedClassRedefinition"
        }
    }
}

ext {
    mod_meta.tenshilib_version = tenshilib_version
}

dependencies {
    implementation "io.github.flemmli97:tenshilib:${tenshilib_version}-neoforge"

    // modRuntimeOnly "${sillib_dep}"
    compileOnly "${powerscale_dep}"

    runtimeOnly "io.github.flemmli97:debugutils:1.21.1-1.0.9-neoforge"
    runtimeOnly "maven.modrinth:jade:2P7THd8J"
    runtimeOnly "curse.maven:moonlight-499980:8215787"
    runtimeOnly "curse.maven:dummy-225738:6608246"
    runtimeOnly "curse.maven:supplementaries-412082:8244187"
    runtimeOnly "io.github.flemmli97:mobbattle:1.21.1-2.6.1-neoforge"
    runtimeOnly "maven.modrinth:tacz-1.21.1:N9ffXNy0"
}
