apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/arch-loom-v2/neoforge.gradle"

loom {
    runs {
        data {
            data()
            programArgs "--all", "--mod", "improvedmobs"
            programArgs "--output", project(":common").file("src/generated/resources").absolutePath
            programArgs "--existing", file("src/main/resources").absolutePath
            programArgs "--existing", project(":common").file("src/main/resources").absolutePath
        }
    }
}

ext {
    mod_meta.tenshilib_version = tenshilib_version
}

dependencies {
    modImplementation "io.github.flemmli97:tenshilib:${tenshilib_version}-neoforge"

    // modRuntimeOnly "${sillib_dep}"
    modCompileOnly "${scalhealth_dep}"
    modRuntimeOnly "io.github.flemmli97:debugutils:1.21.1-1.0.8-neoforge"
    modRuntimeOnly "maven.modrinth:jade:2P7THd8J"
    modRuntimeOnly "curse.maven:moonlight-499980:6682378"
    modRuntimeOnly "curse.maven:dummy-225738:6608246"
    modRuntimeOnly "io.github.flemmli97:mobbattle:1.21.1-2.5.4-neoforge"
}